version: '3'
services:
  cs:
    image: "cassandra:3.11.4"
    container_name: workshop-cs
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_SEEDS=127.0.0.1
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - ./data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50
